# Generated by Django 5.0.6 on 2024-07-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mo_num',
            field=models.CharField(max_length=10),
        ),
    ]
